// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: KKQQ.proto

package testRPC

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type KKQQArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S       string `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	Pointer []byte `protobuf:"bytes,2,opt,name=pointer,proto3" json:"pointer,omitempty"`
}

func (x *KKQQArgs) Reset() {
	*x = KKQQArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KKQQ_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KKQQArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KKQQArgs) ProtoMessage() {}

func (x *KKQQArgs) ProtoReflect() protoreflect.Message {
	mi := &file_KKQQ_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KKQQArgs.ProtoReflect.Descriptor instead.
func (*KKQQArgs) Descriptor() ([]byte, []int) {
	return file_KKQQ_proto_rawDescGZIP(), []int{0}
}

func (x *KKQQArgs) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *KKQQArgs) GetPointer() []byte {
	if x != nil {
		return x.Pointer
	}
	return nil
}

type KKQQReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Pointer []byte `protobuf:"bytes,2,opt,name=pointer,proto3" json:"pointer,omitempty"`
}

func (x *KKQQReply) Reset() {
	*x = KKQQReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KKQQ_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KKQQReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KKQQReply) ProtoMessage() {}

func (x *KKQQReply) ProtoReflect() protoreflect.Message {
	mi := &file_KKQQ_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KKQQReply.ProtoReflect.Descriptor instead.
func (*KKQQReply) Descriptor() ([]byte, []int) {
	return file_KKQQ_proto_rawDescGZIP(), []int{1}
}

func (x *KKQQReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KKQQReply) GetPointer() []byte {
	if x != nil {
		return x.Pointer
	}
	return nil
}

var File_KKQQ_proto protoreflect.FileDescriptor

var file_KKQQ_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x4b, 0x4b, 0x51, 0x51, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x08,
	0x4b, 0x4b, 0x51, 0x51, 0x41, 0x72, 0x67, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x22, 0x3f, 0x0a, 0x09, 0x4b, 0x4b, 0x51, 0x51, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x32, 0x27, 0x0a, 0x04, 0x4b, 0x4b, 0x51, 0x51, 0x12, 0x1f, 0x0a, 0x06, 0x69, 0x73, 0x4b,
	0x4b, 0x51, 0x51, 0x12, 0x09, 0x2e, 0x4b, 0x4b, 0x51, 0x51, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x0a,
	0x2e, 0x4b, 0x4b, 0x51, 0x51, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_KKQQ_proto_rawDescOnce sync.Once
	file_KKQQ_proto_rawDescData = file_KKQQ_proto_rawDesc
)

func file_KKQQ_proto_rawDescGZIP() []byte {
	file_KKQQ_proto_rawDescOnce.Do(func() {
		file_KKQQ_proto_rawDescData = protoimpl.X.CompressGZIP(file_KKQQ_proto_rawDescData)
	})
	return file_KKQQ_proto_rawDescData
}

var file_KKQQ_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_KKQQ_proto_goTypes = []interface{}{
	(*KKQQArgs)(nil),  // 0: KKQQArgs
	(*KKQQReply)(nil), // 1: KKQQReply
}
var file_KKQQ_proto_depIdxs = []int32{
	0, // 0: KKQQ.isKKQQ:input_type -> KKQQArgs
	1, // 1: KKQQ.isKKQQ:output_type -> KKQQReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_KKQQ_proto_init() }
func file_KKQQ_proto_init() {
	if File_KKQQ_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_KKQQ_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KKQQArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KKQQ_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KKQQReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_KKQQ_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_KKQQ_proto_goTypes,
		DependencyIndexes: file_KKQQ_proto_depIdxs,
		MessageInfos:      file_KKQQ_proto_msgTypes,
	}.Build()
	File_KKQQ_proto = out.File
	file_KKQQ_proto_rawDesc = nil
	file_KKQQ_proto_goTypes = nil
	file_KKQQ_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KKQQClient is the client API for KKQQ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KKQQClient interface {
	IsKKQQ(ctx context.Context, in *KKQQArgs, opts ...grpc.CallOption) (*KKQQReply, error)
}

type kKQQClient struct {
	cc grpc.ClientConnInterface
}

func NewKKQQClient(cc grpc.ClientConnInterface) KKQQClient {
	return &kKQQClient{cc}
}

func (c *kKQQClient) IsKKQQ(ctx context.Context, in *KKQQArgs, opts ...grpc.CallOption) (*KKQQReply, error) {
	out := new(KKQQReply)
	err := c.cc.Invoke(ctx, "/KKQQ/isKKQQ", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KKQQServer is the server API for KKQQ service.
type KKQQServer interface {
	IsKKQQ(context.Context, *KKQQArgs) (*KKQQReply, error)
}

// UnimplementedKKQQServer can be embedded to have forward compatible implementations.
type UnimplementedKKQQServer struct {
}

func (*UnimplementedKKQQServer) IsKKQQ(context.Context, *KKQQArgs) (*KKQQReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsKKQQ not implemented")
}

func RegisterKKQQServer(s *grpc.Server, srv KKQQServer) {
	s.RegisterService(&_KKQQ_serviceDesc, srv)
}

func _KKQQ_IsKKQQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KKQQArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KKQQServer).IsKKQQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KKQQ/IsKKQQ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KKQQServer).IsKKQQ(ctx, req.(*KKQQArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _KKQQ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "KKQQ",
	HandlerType: (*KKQQServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "isKKQQ",
			Handler:    _KKQQ_IsKKQQ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "KKQQ.proto",
}
